name: sipo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  charts: ^1.0.0+1
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/book.jpg
  uses-material-design: true
