// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATkW1spQWJa7qZw4GK8OpiPIcpzTC8vyk',
    appId: '1:262100753337:web:924d9b01c7d747709bf468',
    messagingSenderId: '262100753337',
    projectId: 'edukasii-m-y',
    authDomain: 'edukasii-m-y.firebaseapp.com',
    storageBucket: 'edukasii-m-y.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1t-kH8GdkK_X8Hl3UvYpO9fGoc1Ti5N0',
    appId: '1:262100753337:android:b251b901216b736a9bf468',
    messagingSenderId: '262100753337',
    projectId: 'edukasii-m-y',
    storageBucket: 'edukasii-m-y.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTj44bRS878dAI5NIwrWQdaTYK_c_1jHs',
    appId: '1:262100753337:ios:369112742aa656df9bf468',
    messagingSenderId: '262100753337',
    projectId: 'edukasii-m-y',
    storageBucket: 'edukasii-m-y.appspot.com',
    iosBundleId: 'com.example.sipo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTj44bRS878dAI5NIwrWQdaTYK_c_1jHs',
    appId: '1:262100753337:ios:9e133e6c598f25349bf468',
    messagingSenderId: '262100753337',
    projectId: 'edukasii-m-y',
    storageBucket: 'edukasii-m-y.appspot.com',
    iosBundleId: 'com.example.sipo.RunnerTests',
  );
}
